# Generated by Django 3.0 on 2020-11-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TESTING', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
