# Generated by Django 3.0 on 2020-11-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TESTING', '0003_auto_20201111_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
